apiVersion: v1
kind: Service
metadata:
  name: asr-worker
  namespace: modelmesh
spec:
  selector: { app: asr-worker }
  ports:
    - name: http
      port: 8002
      targetPort: 8002
    - name: grpc
      port: 50051
      targetPort: 50051
